# Generated by Django 2.0.1 on 2018-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
