# Generated by Django 2.0.1 on 2018-01-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180105_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
