# Generated by Django 2.0.1 on 2018-01-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180106_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='after_image_link',
            field=models.URLField(default='https://www.stayathomemum.com.au/cache/860x380-0/wp-content/uploads/2015/10/10-Ways-to-Enhance-Your-Homes-Curb-Appeal.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='before_image_link',
            field=models.URLField(default='http://maxmccoy.com/blog/uploaded_images/Greensburg-%28142%29-746217.JPG'),
            preserve_default=False,
        ),
    ]
