# Generated by Django 2.0.1 on 2018-01-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180107_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
